# site basic info
site_name: E5trusw3nt's Notebook
site_author: E5trusw3nt
site_description: "This is E5trusw3nt's Notebook"
copyright: Copyright 2024 by estruswent

# repo
repo_url: "https://github.com/Estruswent/notebook"

# content
nav:
  - 首页: "index.md"
  - Computer Science:
    - 数据结构基础:  
      - "时间复杂度": "数据结构基础/TimeComplexity.md"
      - "双向链表": "数据结构基础/DoublyLinkedList.md"
      - "排序问题（上）": "数据结构基础/Sort2.md"
      - "排序问题（下）": "数据结构基础/Sort1.md"
      - "树、二叉树与线索二叉树": "数据结构基础/Tree.md"
      - "优先队列（堆）": "数据结构基础/PriorityQueues.md"
      - "并查集": "数据结构基础/DisjointSet.md"
      - "图：基本概念": "数据结构基础/Graph_new.md"
      - "图：最短路径算法": "数据结构基础/ShortestPathAlgorithm.md"
      - "图：网络流与最小生成树": "数据结构基础/MST.md"
      - "图：深度优先搜索": "数据结构基础/DFS.md"
      - "待完成": "数据结构基础/unfinished.md"
    - 数据库系统:
      - "Lecture1: Introduction": "数据库系统/Lecture1.md"
      - "Lecture2: relations models and algebra": "数据库系统/Lecture2.md"
      - "Lecture3: SQL": "数据库系统/Lecture3.md"
      - "Lecture4: Immediate SQL": "数据库系统/Lecture4.md"
      - "Lecture5: Advanced SQL": "数据库系统/Lecture5.md"
      - "Lecture6: Database Design using the E-R Model": "数据库系统/Lecture6.md"
      - "Lecture7: Normalization": "数据库系统/Lecture7.md"
      - "Lecture8: Physical Storage System": "数据库系统/Lecture8.md"
      - "Lecture9: Data Storage Structure": "数据库系统/Lecture9.md"
      - "Lecture10: Index": "数据库系统/Lecture10.md"
      - "Lecture11: Query Processing": "数据库系统/Lecture11.md"
      - "Lecture12: Query Optimization": "数据库系统/Lecture12.md"
      - "Lecture13: Transaction": "数据库系统/Lecture13.md"
      - "Lecture14: Concurrency Control": "数据库系统/Lecture14.md"
      - "Lecture15: Recovery System": "数据库系统/Lecture15.md"
    - 面向对象程序设计:
      - "Lecture0: Course Introduction": "面向对象程序设计/Lecture0.md"
      - "Lecture1: Using Objects": "面向对象程序设计/Lecture1.md"
      - "Lecture2: Class": "面向对象程序设计/Lecture2.md"
      - "Lecture3: Object Interactive": "面向对象程序设计/Lecture3.md"
      - "Lecture4: Copy Constructor": "面向对象程序设计/Lecture4.md"
      - "Lecture5: Inheritance": "面向对象程序设计/Lecture5.md"
    - 脑机接口算法及实践:
      - "Lecture0: Introduction": "脑机接口算法及实践/Lecture0.md"
      - "Lecture1: Python EEG Signal": "脑机接口算法及实践/Lecture1.md"
      - "Lecture2: SSVEP": "脑机接口算法及实践/Lecture2.md"
      - "Lecture3: VR-EEG emotion perception": "脑机接口算法及实践/Lecture3.md"
      - "Lecture4: Attention and Emotion": "脑机接口算法及实践/Lecture4.md"
  - Writing:
      - "Latex Introduction": "写作/latex.md"
  - Others:
    - "Matplotlib入门": "其它/Matplotlib.md"
    - "Windows上的子系统“消失不见”": "其它/Explorer不见了.md"

theme:
  name: 'material'
  logo: "style/images/logo.png"
  favicon: 'style/images/favicon.ico'
  palette:     #切换昼夜模式的颜色
    - media: "(prefers-color-scheme: light)" 
      scheme: 'default'  #浅色模式
      # 顶栏
      primary: 'black'
      # 强调色（交互）
      accent: 'indigo'  #强调色
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: 'slate'  #深色模式
      primary: 'black'
      toggle:
        icon: material/weather-night #图标，月亮
        name: Switch to light mode
  features: 
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition # 注解
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true  # 使用 Pygments 进行代码高亮

  - toc:
      title: index
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

extra_javascript:
  - 'style/javascripts/mathjax.js'
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - 'style/css/img.css'
  - 'style/css/code.css'
  - 'style/css/table.css'
  - 'style/css/fonts.css'
  - 'style/css/mermaid.css'
plugins:
  - search
  - mermaid2



language:
  - 'zh'
  - 'en'